version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  taskmanagement.api:
    build:
      context: .
      dockerfile: src/TaskManagement.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskManagementDb;User=sa;Password=YourPassword123!;TrustServerCertificate=true

volumes:
  sqlserver_data:
